apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kalamar-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: kalamar.local
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: kalamar-frontend
                port:
                  number: 80