apiVersion: v1
kind: Service
metadata:
  name: kalamar-sqlserver
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: kalamar-sqlserver
  ports:
    - port: {{ .Values.ports.sqlserver }}
      targetPort: {{ .Values.ports.sqlserver }}
  type: ClusterIP