apiVersion: v1
kind: Service
metadata:
  name: kalamar-task
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: kalamar-task
  ports:
    - port: {{ .Values.ports.task }}
      targetPort: {{ .Values.ports.task }}
  type: ClusterIP